POST http://localhost:3000/produto/incluir 
Content-Type: application/json

{
    "img": "./img/product.png",
    "codBarra": "867900567894",
    "nomeItem": "camiseta2040-",
    "tamanhoItem": "M",
    "precoItem": 39.90,
    "estoque": 3,
    "qtd": 0
}

###

DELETE http://localhost:3000/produto/excluir
Content-Type: application/json

{
    "_id":"629a66d3e34f79aa0c6de190"
}